# Reference: https://cmkr.build/cmake-toml
[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "SaveManager"
description = "The swiss army knife of save management."
version = "1.5.0"
languages = ["C", "CXX"]
msvc-runtime = "dynamic"

[find-package.CURL]
required = true

[find-package.glad]
required = true

[find-package.glfw3]
required = true

[find-package.libzip]
required = true

[find-package.OpenSSL]
required = true

[find-package.Libssh2]
required = true

[find-package.imgui]
required = true

[find-package.nlohmann_json]
required = true

[find-package.stb]
required = true

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true

[target.savemanager]
type = "executable"
sources = [
    "src/**.cpp",
    "vendor/imgui/imgui_stdlib.cpp",
    "vendor/ImGuiFileDialog/*.cpp",
]
include-directories = [
    "src",
    "vendor/imgui",
    "vendor/ImGuiFileDialog",
]
precompile-headers = ["src/pch.hpp"]
link-libraries = ["CURL::libcurl", "glfw", "libzip::zip", "Libssh2::libssh2", "OpenSSL::Crypto", "imgui::imgui", "glad::glad", "nlohmann_json::nlohmann_json", "stb::stb"]
compile-features = ["cxx_std_23"]
cmake-after = """
find_path(IMGUI_INCLUDE_DIR imgui.h REQUIRED)
cmake_path(GET IMGUI_INCLUDE_DIR PARENT_PATH IMGUI_ROOT_DIR)
target_include_directories(savemanager PRIVATE "${IMGUI_ROOT_DIR}/res/bindings")
target_sources(savemanager PRIVATE
    "${IMGUI_ROOT_DIR}/res/bindings/imgui_impl_glfw.cpp"
    "${IMGUI_ROOT_DIR}/res/bindings/imgui_impl_opengl3.cpp"
)
"""

[target.savemanager.windows]
link-libraries = ["ws2_32", "shell32"]
