# Reference: https://cmkr.build/cmake-toml
[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "SaveManager"
description = "The swiss army knife of save management."
version = "1.3.0"
languages = ["C", "CXX"]

[vcpkg]
version = "2026.02.27"
packages = ["curl", "glfw3", "libzip", "libssh2", "openssl"]

[find-package.CURL]
required = true

[find-package.glfw3]
required = true

[find-package.libzip]
required = true

[find-package.OpenSSL]
required = true

[find-package.libssh2]
required = true

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true

[target.savemanager]
type = "executable"
sources = [
    "src/**.cpp",

    # Dear ImGui
    "external/imgui/imgui.cpp",
    "external/imgui/imgui_draw.cpp",
    "external/imgui/imgui_tables.cpp",
    "external/imgui/imgui_widgets.cpp",
    "external/imgui/backends/imgui_impl_glfw.cpp",
    "external/imgui/backends/imgui_impl_opengl3.cpp",
    "external/imgui/misc/cpp/imgui_stdlib.cpp",

    # GLAD
    "external/glad/src/glad.c",
]
include-directories = [
    "external",
    "external/imgui",
    "external/imgui/backends",
    "external/glad/include",
    "src",
]
precompile-headers = ["src/pch.hpp"]
link-libraries = ["CURL::libcurl", "glfw", "libzip::zip", "libssh2::libssh2", "OpenSSL::Crypto"]
compile-features = ["cxx_std_17"]

[target.savemanager.windows]
link-libraries = ["ws2_32"]
