#pragma once

enum class SMError {
    PATH_NOT_FOUND,
    PERMISSION_DENIED,
    NO_SAVES_FOUND,
    CONFIG_PARSING_ERROR,
    CONFIG_LOAD_ERROR,
    CONNECTION_FAILED,
    DOWNLOAD_FAILED,
    PLUGIN_LOAD_ERROR,
};
