blank_issues_enabled: false
contact_links:
  - name: Questions & Ideas
    url: https://github.com/msh31/SaveManager/discussions/new/choose
    about: For general questions or feature ideas, please start a discussion first.
