name: Build Test

on:
  workflow_dispatch:
  push: 
    branches: [ dev ]
  pull_request: 
    branches: [ main, dev ]

concurrency:
  group: build-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
